### ISSUE TITLE
Is socket.io version 4.x.x fully supported?

### ISSUE THREAD

**Issue by nmargaritis** [darrachequesne/socket.io-msgpack-parser#7]
The version 4 did not introduce any changes to the topic of parsers, but since you explicitly mention support in your readme file, I believe that this question can be crosschecked and possibly result in an updated readme file.

**Comment by darrachequesne** [comment]
Hi! The current version of the parser is indeed compatible with Socket.IO v4, I've updated the compatibility table accordingly.

Thanks for the heads-up.
